AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Provisiona a função AWS Lambda para Base de Conhecimento.
  Apenas Rota e Integração (O Stage é gerenciado pela Infra).

Parameters:
  EcrRepositoryName:
    Type: String
    Description: 'Nome do repositório ECR'
  ImageTag:
    Type: String
    Default: latest
    Description: 'Tag da imagem Docker'
  LambdaName:
    Type: String
    Default: lbd-spotispec-base-conhecimento
    Description: 'Nome da função Lambda'
  ApiGatewayId: 
    Type: String
    Description: 'ID da API Gateway V2 (HTTP API)'

Resources:

  ## 1. IAM Role 
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ECRAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: "*"

  ## 2. Função Lambda 
  FastApiLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaName
      Role: !GetAtt LambdaExecutionRole.Arn
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EcrRepositoryName}:${ImageTag}"
      MemorySize: 512
      Timeout: 30

  ## 3. Integração e Rotas
  
  LambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiGatewayId
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FastApiLambdaFunction.Arn}/invocations"
      PayloadFormatVersion: "2.0"
      
  KnowledgeBaseRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGatewayId
      RouteKey: "POST /base-conhecimento" 
      Target: !Sub "integrations/${LambdaIntegration}"
      
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref FastApiLambdaFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayId}/*/*"

  OptionsKnowledgeBaseRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGatewayId
      RouteKey: "OPTIONS /base-conhecimento"
      Target: !Sub "integrations/${LambdaIntegration}"
      
Outputs:
  LambdaFunctionName:
    Description: "Nome da Função Lambda Criada"
    Value: !Ref FastApiLambdaFunction